# Домашнее задание 1

## Норма Минковского 

### Бобков Владислав, группа 1384

Вариант 2

1. Теорема Минковского: Если $W$  — выпуклое множество, то выражение $||x|| = inf \{ \lambda : \frac{x}{\lambda} \in W, \lambda > 0\}$ задает норму в этом пространстве.

Нужно проверить выпуклость множества, заданного в условии задачи 



По условию задачи, В R^3 задан многогранник W и две точки x и y. 
Требуется вычислить норму Минковского для ||x|| , ||y|| и ||x+y||

In [143]:
import numpy as np
from sympy import *

In [144]:
# точки согласно 2 варианту
A = np.array((13,0,0)).T
B = np.array((0,19,0)).T
C = np.array((0,0,16)).T
D = np.array((8,10,0)).T
E = np.array((12,0,11)).T
G = np.array((0,7,9)).T

dots = np.array(symbols('x y z')).T

# нахождение уравнения плоскости по трем точкам
def find_surface(x,y,z):
    V1 = (y - x)
    V2 = (z - x)
    
    # Нахождение коэффициентов нормали к плоскости (коэффициенты A B C в уравнении плоскости)
    normal = np.cross(V1,V2)
    surface = normal @ (dots - x)
    return surface

surfaces = [
    find_surface(A,D,E),
    find_surface(C,E,G),
    find_surface(B,D,G),
    find_surface(D,E,G)
]

for s in surfaces: 
    print(f" {s} = 0")
    
start_vertexes = [A,B,C,D,E,G]
vertexes = []


 110*x + 55*y + 10*z - 1430 = 0
 35*x + 84*y + 84*z - 1344 = 0
 -81*x - 72*y - 96*z + 1368 = 0
 -57*x - 124*y - 92*z + 1696 = 0


Уравнения плоскостей были получены. Остальные вершины получаются зеркальным отражением относительно координатных плоскостей
То есть если v=(a,b,c) вершина, то и u=(+-a,+-b,+-c) тоже вершина. Всего 18 вершин.

In [145]:
def find_all_vertexes():
    global vertexes
    for dot in start_vertexes:
        for x in [-1, 1]:
            for y in [-1, 1]:
                for z in [-1, 1]:
                    temp = np.array([x* dot[0], y * dot[1], z * dot[2]]).T     
                    vertexes.append(temp)
    matrices_array = np.array(vertexes)
    unique_matrices_array = np.unique(matrices_array, axis=0)
    vertexes = unique_matrices_array.tolist()
                
find_all_vertexes()

print(vertexes)

[[-13, 0, 0], [-12, 0, -11], [-12, 0, 11], [-8, -10, 0], [-8, 10, 0], [0, -19, 0], [0, -7, -9], [0, -7, 9], [0, 0, -16], [0, 0, 16], [0, 7, -9], [0, 7, 9], [0, 19, 0], [8, -10, 0], [8, 10, 0], [12, 0, -11], [12, 0, 11], [13, 0, 0]]


Теперь нужно проверить выпуклость данного многогранника.
Многогранник выпуклый, если выполнено условие: для любой плоскости грани все вершины лежат в одном полупространстве.
У W 32 грани, но в силу симметрии, достаточно проверить грани в первом квадранте.
Надо составить уравнения плоскостей граней (плоскость через 3 точки)


In [146]:
#проверка выпуклости(достаточно проверить только 1 квадрант в силу симметричности)
(x,y,z) = symbols('x y z')

def check_bulge(surface, vertexes):
    results = []
    #print(vertexes)
    for x1,y1,z1 in vertexes:
        temp = surface.subs({x : x1, y : y1, z : z1})
        if temp == 0:
            print(0, end = " ")
        elif temp > 0:
            results.append(1)
            print("+",end = " ")
        else:
            results.append(0)
            print("-", end=" ")
        if 0 in results and 1 in results:
            return False
    return True

for s in surfaces:
    print("Уравнение плоскости: ", s)
    print(check_bulge(s,vertexes))

Уравнение плоскости:  110*x + 55*y + 10*z - 1430
- - - - - - - - - - - - - - 0 - 0 0 True
Уравнение плоскости:  35*x + 84*y + 84*z - 1344
- - - - - - - - - 0 - 0 + False
Уравнение плоскости:  -81*x - 72*y - 96*z + 1368
+ + + + + + + + + - False
Уравнение плоскости:  -57*x - 124*y - 92*z + 1696
+ + + + + + + + + + + 0 - False


Как видно, многогранник нельзя назвать выпуклым, поэтому нужно поменять какие-то координаты. Как пример, можно поменять координаты точки G на (0,15,9)

In [147]:
G = np.array((0,15,9)).T
surfaces = [
    find_surface(A,D,E),
    find_surface(C,E,G),
    find_surface(B,D,G),
    find_surface(D,E,G)
]
vertexes = []

find_all_vertexes()

for i in surfaces:
    print("Уравнение плоскости: ", i)
    print(check_bulge(i,vertexes),end='\n\n')


Уравнение плоскости:  110*x + 55*y + 10*z - 1430
- - - - - - - - - - - - - - 0 - 0 0 True

Уравнение плоскости:  75*x + 84*y + 180*z - 2880
- - - - - - - - - 0 - - - - - - 0 - True

Уравнение плоскости:  -81*x - 72*y - 32*z + 1368
+ + + + + + + + + + + + 0 + 0 + + + True

Уравнение плоскости:  -145*x - 124*y - 60*z + 2400
+ + + + + + + + + + + + + + 0 + 0 + True



Теперь многогранник можно назвать выпуклым, все условия теоремы Минковского выполнены, можно считать норму Минковского для векторов X, Y, X + Y

In [149]:
X = -A[0] * A + E[2] * E
Y = C[2] * C - D[1] * D
Z = X + Y

def make_positive(m):
    for i in range(len(m)):
        if m[i] < 0:
            m[i] *=-1
            
make_positive(X)
make_positive(Y)
make_positive(Z)

print(X,Y,Z, sep='\n')

A1 = np.cross(E,D) / (np.cross(E,D) @ A)
E1 = np.cross(A,D) / (np.cross(A,D) @ E)
D1 = np.cross(A,E) / (np.cross(A,E) @ D)

ax1 = np.round(X @ A1,10)
bx1 = np.round(X @ E1)
cx1 = np.round(X @ D1)

#print(ax1,bx1,cx1)

ay1 =np.round( Y @ A1,10)
by1 = np.round(Y @ E1,10)
cy1 = np.round(Y @ D1,10)

#print(ay1,by1,cy1)

az1 = np.round(Z @ A1,10)
bz1 = np.round(Z @ E1,10)
cz1 = np.round(Z @ D1,10)

#print(az1,bz1,cz1)

D2 = np.cross(E,G) / (np.cross(E,G) @ D)
E2 = np.cross(G,D) / (np.cross(G,D) @ E)
G2 = np.cross(E,D) / (np.cross(E,D) @ G)

ax2 = np.round(X @ D2,10)
bx2 = np.round(X @ E2,10)
cx2 = np.round(X @ G2, 10)


ay2 = np.round(Y @ D2,10)
by2 = np.round(Y @ E2,10)
cy2 = np.round(Y @ G2,10)


az2 = np.round(Z @ D2,10)
bz2 = np.round(Z @ E2,10)
cz2 = np.round(Z @ G2,10)


B3 = np.cross(G,D) / (np.cross(G,D) @ B)
D3 = np.cross(B,G) / (np.cross(B,G) @ D)
G3 = np.cross(B,D) / (np.cross(B,D) @ G)

ax3 = np.round(X @ B3,10)
bx3 = np.round(X @ D3,10)
cx3 = np.round(X @ G3,10)

ay3 = np.round(Y @ B3,10)
by3 = np.round(Y @ D3,10)
cy3 = np.round(Y @ G3,10)

az3 = np.round(Z @ B3,10)
bz3 = np.round(Z @ D3,10)
cz3 = np.round(Z @ G3,10)

C4 = np.cross(E,G) / (np.cross(E,G) @ C)
E4 = np.cross(C,G) / (np.cross(C,G) @ E)
G4 = np.cross(E,C) / (np.cross(E,C) @ G)

ax4 = np.round(X @ C4,10)
bx4 = np.round(X @ E4,10)
cx4 = np.round(X @ G2,10)
print(ax4,bx4,cx4,ax4+bx4+cx4)
ay4 = np.round(Y @ C4,10)
by4 = np.round(Y @ E4,10)
cy4 = np.round(Y @ G4,10)
print(ay4,by4,cy4,ay4+by4+cy4)
az4 = np.round(Z @ C4,10)
bz4 = np.round(Z @ E4,10)
cz4 = np.round(Z @ G4,10)
print(az4,bz4,cz4,az4+bz4+cz4)


[ 37   0 121]
[ 80 100 256]
[117 100 377]
5.4427083333 3.0833333333 4.3541666667 12.8802083333
7.6666666667 6.6666666667 6.6666666667 21.000000000100002
13.109375 9.75 6.6666666667 29.5260416667


Для вычисления нормы Минковского точки X надо знать, какую из граней пересекает отрезок 0X, иными словами, в конусе какой грани лежит точка X.

Для этого необходимо разложить вектор по базису, задаваемым вершинами при грани. Пусть v1,v2,v3, - базис, задаваемый вершинами на грани. Тогда, если $x = \alpha_1 x_1 + \alpha_2 x_2 + \alpha_3 x_3$ и все $\alpha$ будут положительными, данная грань будет ближайшей к X 

Для того, чтобы найти $\alpha$ воспользуемся биортогональным базисом - таким набором векторов $u_i$, что $(u_i,v_j) = 0, j != i и (u_i,v_i) = 1$, тогда $\alpha_i = (x_i,u_i)$

Легко проверить, что в трёхмерном случае данным требованиям удовлетворяет набор векторов, заданный как  $u_i = \frac{v_j \times v_k}{(v_j \times v_k,v_i)}$

Норма Минковского будет равна сумме полученных коэффициентов.